insert into Songs (Title, Artist, genre) values ('Jolene', 'Matthew Thomas', 'metal');
insert into Songs (Title, Artist, genre) values ('Killing Me Softly', 'Michael Davis', 'classical');
insert into Songs (Title, Artist, genre) values ('Shape of You', 'John Smith', 'electronic');
insert into Songs (Title, Artist, genre) values ('XO', 'David Wilson', 'rock');
insert into Songs (Title, Artist, genre) values ('Can''t Stop the Feeling!', 'Ava Garcia', 'pop');
insert into Songs (Title, Artist, genre) values ('Rolling in the Deep', 'Matthew Thomas', 'electronic');
insert into Songs (Title, Artist, genre) values ('Let It Be', 'Matthew Thomas', 'hip hop');
insert into Songs (Title, Artist, genre) values ('XO', 'Emma Taylor', 'rock');
insert into Songs (Title, Artist, genre) values ('Firework', 'Ava Garcia', 'classical');
insert into Songs (Title, Artist, genre) values ('Margaritaville', 'David Wilson', 'indie');
insert into Songs (Title, Artist, genre) values ('Can''t Stop the Feeling!', 'Daniel Anderson', 'pop');
insert into Songs (Title, Artist, genre) values ('Mamma Mia', 'Ava Garcia', 'jazz');
insert into Songs (Title, Artist, genre) values ('Can''t Stop the Feeling!', 'Emily Johnson', 'classical');
insert into Songs (Title, Artist, genre) values ('Oops!... I Did It Again', 'David Wilson', 'rock');
insert into Songs (Title, Artist, genre) values ('Zombie', 'Sophia Thompson', 'rock');
insert into Songs (Title, Artist, genre) values ('Call Me Maybe', 'David Wilson', 'hip hop');
insert into Songs (Title, Artist, genre) values ('Hey Jude', 'Emma Taylor', 'hip hop');
insert into Songs (Title, Artist, genre) values ('Livin'' on a Prayer', 'Matthew Thomas', 'country');
insert into Songs (Title, Artist, genre) values ('Let It Be', 'Emma Taylor', 'classical');
insert into Songs (Title, Artist, genre) values ('I Will Always Love You', 'Michael Davis', 'classical');
insert into Songs (Title, Artist, genre) values ('No Woman', 'John Smith', 'country');
insert into Songs (Title, Artist, genre) values ('Killing Me Softly', 'Emily Johnson', 'classical');
insert into Songs (Title, Artist, genre) values ('Viva la Vida', 'Emma Taylor', 'indie');
insert into Songs (Title, Artist, genre) values ('Mamma Mia', 'John Smith', 'metal');
insert into Songs (Title, Artist, genre) values ('All About That Bass', 'Michael Davis', 'reggae');
insert into Songs (Title, Artist, genre) values ('A Thousand Miles', 'Matthew Thomas', 'rock');
insert into Songs (Title, Artist, genre) values ('Thriller', 'Sophia Thompson', 'rock');
insert into Songs (Title, Artist, genre) values ('Just the Way You Are', 'Sophia Thompson', 'jazz');
insert into Songs (Title, Artist, genre) values ('Hey Jude', 'Olivia Martinez', 'jazz');
insert into Songs (Title, Artist, genre) values ('Just the Way You Are', 'Olivia Martinez', 'pop');
insert into Songs (Title, Artist, genre) values ('Zombie', 'David Wilson', 'jazz');
insert into Songs (Title, Artist, genre) values ('Kiss from a Rose', 'Emma Taylor', 'electronic');
insert into Songs (Title, Artist, genre) values ('Oops!... I Did It Again', 'Daniel Anderson', 'electronic');
insert into Songs (Title, Artist, genre) values ('Kiss from a Rose', 'Michael Davis', 'jazz');
insert into Songs (Title, Artist, genre) values ('Gangnam Style', 'Matthew Thomas', 'classical');
insert into Songs (Title, Artist, genre) values ('Oops!... I Did It Again', 'Michael Davis', 'pop');
insert into Songs (Title, Artist, genre) values ('All About That Bass', 'Daniel Anderson', 'metal');
insert into Songs (Title, Artist, genre) values ('Proud Mary', 'Michael Davis', 'pop');
insert into Songs (Title, Artist, genre) values ('Yellow', 'Michael Davis', 'rock');
insert into Songs (Title, Artist, genre) values ('Can''t Stop the Feeling!', 'Emma Taylor', 'country');
insert into Songs (Title, Artist, genre) values ('A Thousand Miles', 'Matthew Thomas', 'indie');
insert into Songs (Title, Artist, genre) values ('Just the Way You Are', 'Olivia Martinez', 'pop');
insert into Songs (Title, Artist, genre) values ('No Cry', 'Daniel Anderson', 'hip hop');
insert into Songs (Title, Artist, genre) values ('Bad Romance', 'Ava Garcia', 'classical');
insert into Songs (Title, Artist, genre) values ('Hey Jude', 'Matthew Thomas', 'pop');
insert into Songs (Title, Artist, genre) values ('I Want to Hold Your Hand', 'Olivia Martinez', 'metal');
insert into Songs (Title, Artist, genre) values ('Piano Man', 'Matthew Thomas', 'classical');
insert into Songs (Title, Artist, genre) values ('Fancy', 'Emma Taylor', 'electronic');
insert into Songs (Title, Artist, genre) values ('Uptown Funk', 'Michael Davis', 'jazz');
insert into Songs (Title, Artist, genre) values ('Uptown Funk', 'David Wilson', 'hip hop');
